Repository DC23/jd-easytimekeeping, pull requests merged in 2024-11, with the labels that each got.

#34 18 dawndusk scene lighting
  .gitignore
  .prettierrc
  lang/en.json
  src/autotelltimemenu.js
  src/clockview.js
  src/daylightcycle.js
  src/daylightcyclesettings.js
  src/initialisation.js
  src/settings.js
  src/timekeeper.js
  styles/settings.css
  templates/autotelltimesettings.hbs
  templates/daylightcyclesettings.hbs
Labels: enhancement, core feature

#135 GitHub Action to automate Change Log Creation
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: core feature

#141 132 hiding time of day also hides the day counter
  lang/en.json
  lang/fr.json
  src/initialisation.mjs
  src/uipanel.mjs
  styles/easy-timekeeping.css
  templates/uipanel.hbs
Labels: enhancement

#142 Moving settings registration to the `i18nInit` hook.
  src/initialisation.mjs
Labels: bug

#145 Renamed the GM setting controlling player visibility of the exact time for improved clarity of use
  lang/en.json
  lang/fr.json
  src/helpers.mjs
  src/settings.mjs
  src/timekeeper.mjs
Labels: refactoring

#146 Fixed Assistant GM doesn't see the exact time issue.
  src/uipanel.mjs
Labels: bug

#151 fixed integer arithmetic error in day and week calculation
  src/uipanel.mjs
Labels: bug

#153 Fixed shift and day clock bug. They now transition smoothly.
  src/uipanel.mjs
Labels: bug

#159 Maintenance on the release drafter workflow
  .github/workflows/release-drafter.yml
Labels: maintenance

#161 Added documentation category to Release Drafter workflow
  .github/release-drafter.yml
Labels: maintenance

#162 Added option to fade the UI when it's not being used
  lang/en.json
  lang/fr.json
  src/settings.mjs
  src/uipanel.mjs
  styles/easy-timekeeping.css
  templates/uipanel.hbs
Labels: core feature

#166 UI cosmetic settings are now user-level client settings instead of GM-level world settings. Also added background color for clocks.
  lang/en.json
  lang/fr.json
  src/settings.mjs
  src/uipanel.mjs
Labels: enhancement

#167 Updated Readme images with newer and cleaner versions that match latest module features
  README.md
  documentation/img/afternoon-clock.png
  documentation/img/evening-clock.png
  documentation/img/gm-all-ui.png
  documentation/img/gm-default-ui.png
  documentation/img/morning-clock.png
  documentation/img/night-clock.png
  documentation/img/player-default-ui.png
  documentation/img/player-dragonbane-graphical.png
  documentation/img/player-fuzzy-dragonbane.png
  styles/easy-timekeeping.css
Labels: documentation

#168 Updated French translation ## 0.8.0
  lang/fr.json
Labels: bug

#176 Fixed broken workflow badges on GitHub readme
  README.md
Labels: maintenance

#177 Added 2px gap between graphical clocks to improve visual appearance
  styles/easy-timekeeping.css
Labels: bug

#179 Fixed issue where UI appeared in the wrong location when Foundry A/V Chat was enabled
  src/initialisation.mjs
  src/uipanel.mjs
  styles/easy-timekeeping.css
Labels: bug

#181 Fixed incorrect time display when changing scenes
  src/uipanel.mjs
Labels: bug

#183 Fixed broken UI fading after changing scenes
  src/uipanel.mjs
Labels: bug

#187 Improved readme stats to streamline releases
  .bumpversion.cfg
  README.md
Labels: maintenance

#189 Added client setting for including day in the exact time. By default, the day is not shown anymore. You can restore the old behaviour in the settings.
  lang/en.json
  lang/fr.json
  src/settings.mjs
  src/uipanel.mjs
Labels: enhancement

#191 Made more cosmetic settings player-facing: 12 or 24-hour time (only effective when the GM allows players to see the exact time), and some default setting values
  lang/en.json
  src/settings.mjs
Labels: enhancement

#198 added language strings for days of the week
  lang/en.json
  lang/fr.json
Labels: core feature

#199 Updated links in readme badges
  README.md
Labels: maintenance

#201 Added latest release downloads badge
  README.md
Labels: documentation

#204 Implemented customizable named days of the week
  lang/en.json
  lang/fr.json
  src/helpers.mjs
  src/settings.mjs
  src/timekeeper.mjs
  src/uipanel.mjs
  src/weekdaysettings.mjs
  templates/weekdaysettings.hbs
Labels: enhancement

#206 Updated the long-format time display to include named days of the week
  documentation/timekeeper.md
  lang/en.json
  lang/fr.json
  src/constants.mjs
  src/helpers.mjs
  src/settings.mjs
  src/timekeeper.mjs
  src/timeteller.mjs
  src/uipanel.mjs
Labels: enhancement

#207 190 add keyboard modifiers that will make time steps have double or half the effect
  README.md
  src/uipanel.mjs
Labels: core feature

#208 Added customisable colors to the GM time buttons. There are three colors: the passive button, hovered, and clicked.
  lang/en.json
  lang/fr.json
  src/settings.mjs
  src/uipanel.mjs
  styles/easy-timekeeping.css
  templates/uipanel.hbs
Labels: enhancement

#210 Fixed a bug in the new button color feature and made the time step button color settings GM-only
  src/settings.mjs
  src/uipanel.mjs
Labels: bug

#211 Fixed bug where GM-only settings were being shown to players
  src/settings.mjs
  src/shiftsettings.mjs
  src/weekdaysettings.mjs
Labels: bug

#212 Fixed UI disappearing when the AV Dock position is changed
  src/uipanel.mjs
Labels: bug

#214 Fixed Set Time validation bug that wouldn't let all times be set
  templates/setTimeDialog.hbs
Labels: bug

#215 Added reset to defaults buttons to settings menus
  src/daylightcyclesettings.mjs
  src/shiftsettings.mjs
  src/weekdaysettings.mjs
  templates/daylightcyclesettings.hbs
  templates/shiftsettings.hbs
  templates/weekdaysettings.hbs
Labels: core feature

#219 Updated French language strings for v0.9 features
  lang/fr.json
Labels: bug

#225 Added open bugs badge. I aim to keep it at 0.
  README.md
Labels: enhancement

#226 Cleaned up project plumbing. Removed old bumpversion configuration and updated `module.json` on main branch to indicate that it's not the version that should be installed.
  .bumpversion.cfg
  module.json
Labels: maintenance

#228 Added Foundry default reminder about the Save Changes button being needed after using the Reset Defaults button on a settings form.
  src/daylightcyclesettings.mjs
  src/shiftsettings.mjs
  src/weekdaysettings.mjs
Labels: enhancement

#229 Added Sasmira to authors as thanks for all their work keeping the French translation up to date, bug fixes, testing, and ideas.
  module.json
Labels: documentation

#232 Added edited, labeled, & unlabeled types to release drafter workflow
  .github/workflows/release-drafter.yml
Labels: maintenance

#235 Fixed contradictory text in readme.
  README.md
Labels: documentation

#236 Rename French language to Français in manifest
  module.json
Labels: documentation

#239 Updated release creation workflow so `draft` and `prerelease` values take their values from the event context
  .github/workflows/release-creation.yml
Labels: maintenance
