Repository DC23/jd-easytimekeeping, pull requests merged in 2024-12, with the labels that each got.

#242 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#243 Fixed minor typos in documentation - missing URL in Contributing.md, & heading markup in license
  CONTRIBUTING.md
  LICENSE
Labels: documentation

#244 When the daylight cycle is first enabled, it checks the time immediately instead of waiting until the next time change
  src/daylightcyclesettings.mjs
Labels: bug

#245 All daylight cycle logging is now debug level
  src/daylightcycle.mjs
Labels: maintenance

#246 Added customisable week name
  lang/en.json
  lang/fr.json
  src/helpers.mjs
  src/initialisation.mjs
  src/uipanel.mjs
  src/weekdaysettings.mjs
Labels: core feature

#248 Implemented customisable game turns instead of fixed duration stretches. The default is Dragonbane "stretch"/15 minutes.
  lang/en.json
  src/constants.mjs
  src/settings.mjs
  src/uipanel.mjs
  templates/uipanel.hbs
Labels: core feature

#249 Add new API function that calculates game turns, shifts, days, and weeks from the elapsed minutes since 12am on day 0.
  documentation/timekeeper.md
  src/helpers.mjs
  src/timekeeper.mjs
  src/uipanel.mjs
  templates/uipanel.hbs
Labels: core feature

#251 Added hotkey to hide and show the UI window
  lang/en.json
  src/uipanel.mjs
  styles/easy-timekeeping.css
  templates/uipanel.hbs
Labels: core feature

#254 Added optional floating UI panel which can be moved around on the canvas
  lang/en.json
  src/initialisation.mjs
  src/settings.mjs
  src/uipanel.mjs
  styles/easy-timekeeping.css
Labels: core feature

#255 Fixing UI issues when Foundry Audio/Video is enabled. The module detects this and automatically switches to the floating panel.
  src/timekeeper.mjs
  src/uipanel.mjs
Labels: bug

#256 252 add a button to the UI that posts the current time to the chat window
  lang/en.json
  lang/fr.json
  src/uipanel.mjs
  styles/easy-timekeeping.css
  templates/uipanel.hbs
Labels: core feature

#258 Fixed bug where UI did not appear when loading a world with no active scene.
  src/initialisation.mjs
Labels: bug

#260 Fixed bug with initial floating UI position when loading a world with no active scene.
  src/uipanel.mjs
Labels: bug

#262 Fixed bug where the toggle UI hotkey sometimes had to be pressed twice to show the UI after it was closed manually.
  src/uipanel.mjs
Labels: bug

#264 Fixed missing French translation strings, and fixed floating window background color to black.
  lang/fr.json
  styles/easy-timekeeping.css
Labels: bug

#266 Integration patch for recent PR. A couple of minor styles are only applied to the floating panel.
  src/uipanel.mjs
  styles/easy-timekeeping.css
Labels: enhancement

#280 Refactored the `Constants` class to change from "stretch" to "turn"
  README.md
  src/constants.mjs
  src/helpers.mjs
  src/timekeeper.mjs
  src/uipanel.mjs
Labels: refactoring

#275 Added Italian translation.
  lang/it.json
Labels: enhancement

#274 Update module configuration to enable Italian language support.
  module.json
Labels: maintenance

#281 Updated Contribution guidelines with a section for translators and elaborated on the goal of focused pull requests.
  CONTRIBUTING.md
Labels: documentation

#284 Refactored code to use `Constants.daysPerWeek` instead of hard-coded 7-day weeks.
  src/helpers.mjs
  src/timekeeper.mjs
  src/uipanel.mjs
Labels: refactoring

#285 Added the missing time constants to API documentation.
  Makefile
  documentation/timekeeper.md
  src/constants.mjs
  src/daylightcycle.mjs
  src/helpers.mjs
Labels: documentation

#286 Reset time dialog is no longer modal.
  src/uipanel.mjs
Labels: bug

#287 Fixed a couple of minor CSS issues with the main undocked UI and set time dialog.
  src/settimeapp.mjs
  styles/easy-timekeeping.css
Labels: bug

#288 Fixed inconsistent type capitalization in API docs
  documentation/timekeeper.md
  src/constants.mjs
Labels: documentation

#291 Added a client setting for the circular clock border and spoke colour.
  lang/en.json
  lang/fr.json
  lang/it.json
  src/settings.mjs
  src/uipanel.mjs
  styles/easy-timekeeping.css
  templates/uipanel.hbs
Labels: core feature

#293 Client-only cosmetic settings are now applied without a Foundry reload.
  src/settings.mjs
  src/uipanel.mjs
  styles/easy-timekeeping.css
Labels: core feature

#295 Added client setting for floating ui panel opacity when it has focus.
  lang/en.json
  lang/fr.json
  lang/it.json
  src/settings.mjs
  src/uipanel.mjs
Labels: core feature

#296 Added a client setting for the UI background colour.
  lang/en.json
  lang/fr.json
  lang/it.json
  src/settings.mjs
  src/uipanel.mjs
  styles/easy-timekeeping.css
Labels: core feature

#297 Adding compendium workflow that will allow me to add example macros.
  .github/workflows/release-creation.yml
  Makefile
  module.json
  package-lock.json
  package.json
  src/packs/macros/folders_API_Examples_nRVMmmg6fU1eP7V7.yml
  src/packs/macros/macros_Decrement_1_day_IrLTINsJVEwAetDl.yml
  src/packs/macros/macros_Increment_1_day_luHhYriJDLCj3Uqo.yml
  src/packs/macros/macros_Reset_Time_YeTrhIo842S81Gfs.yml
  src/packs/macros/macros_Set_to_11_30am_on_day_2_WooxymkquvOrxcjS.yml
  tools/pullYMLtoLDB.mjs
  tools/pushLDBtoYML.mjs
Labels: maintenance

#299 Adding names to unnamed workflow steps.
  .github/workflows/release-creation.yml
Labels: refactoring

#300 Added compendium with example macros for all the API functions.
  documentation/timekeeper.md
  src/packs/macros/folders_Basic_API_Functions_Yfu68cdycaDj0W5C.yml
  src/packs/macros/macros_Decrement_1_day_IrLTINsJVEwAetDl.yml
  src/packs/macros/macros_Increment_1_day_luHhYriJDLCj3Uqo.yml
  src/packs/macros/macros_Reset_Time_YeTrhIo842S81Gfs.yml
  src/packs/macros/macros_Set_to_11_30am_on_day_2_WooxymkquvOrxcjS.yml
  src/packs/macros/macros_Tell_Time_xO1PIncAFVsbPLc0.yml
  src/packs/macros/macros_factorGameTurns_ImCJp1Ilikq8Z4tm.yml
  src/packs/macros/macros_getPhaseOfDay_mFLZqXxvuxWE81zM.yml
  src/packs/macros/macros_getTime_ECEuVeVi2NGkvcTP.yml
  src/packs/macros/macros_increment_A2dShvgSaIKQBON1.yml
  src/packs/macros/macros_increment___no_arguments_I4pjnPXyQfv39Tys.yml
  src/packs/macros/macros_increment___reduce_the_time_KUGnux9isV3D1TW7.yml
  src/packs/macros/macros_set_1xtNC0iy6UtfGAoY.yml
  src/packs/macros/macros_toTimeString_2y7tBcywzeDuXc8E.yml
  src/timekeeper.mjs
Labels: documentation

#302 Implemented support for variable length weeks with customisable names of the days.
  lang/en.json
  lang/fr.json
  lang/it.json
  src/constants.mjs
  src/helpers.mjs
  src/settings.mjs
  src/weekdaysettings.mjs
  templates/weekdaysettings.hbs
Labels: core feature

#304 v1.2.0 it.json
  lang/it.json
Labels: core feature

#306 UI should now remain the correct size while long text wraps to multiple lines.
  src/uipanel.mjs
  styles/easy-timekeeping.css
  templates/uipanel.hbs
Labels: bug

#308 Another bugfix to the floating UI. Horizontal resizing should now work, and horizontal size should initialise correctly. Also reduced internal padding to give more room to display the time.
  src/uipanel.mjs
  styles/easy-timekeeping.css
Labels: bug

#310 Added check for missing DOM element when first rendering UI
  src/uipanel.mjs
Labels: bug

#312 Updating example macros & renaming compendium
  module.json
  src/packs/macros/macros_getPhaseOfDay_mFLZqXxvuxWE81zM.yml
  src/packs/macros/macros_increment_A2dShvgSaIKQBON1.yml
  src/packs/macros/macros_increment___no_arguments_I4pjnPXyQfv39Tys.yml
  src/packs/macros/macros_increment___reduce_the_time_KUGnux9isV3D1TW7.yml
  src/packs/macros/macros_set_1xtNC0iy6UtfGAoY.yml
Labels: enhancement

#314 Updated release workflow to `devops-actions/variable-substitution` since the old Action has been deprecated.
  .github/workflows/release-creation.yml
Labels: maintenance

#317 Update French translations.
  lang/fr.json
Labels: enhancement
