Repository DC23/jd-easytimekeeping, pull requests merged in 2025-04, with the labels that each got.

#334 Foundry v13 compatibility fixes
  module.json
  src/settimeapp.mjs
Labels: maintenance

#336 Added check for absence of scene in daylight cycle time change handler
  src/daylightcycle.mjs
Labels: bug

#337 Adding example time change handler macro
  src/packs/macros/folders_Time_Change_Handler_nL4GactRADbRkcfw.yml
  src/packs/macros/macros_timeChangeHandler_aVzIsbEmo7cOq77U.yml
Labels: documentation

#339 218 the post time to chat feature should have a customisable string
  lang/en.json
  lang/fr.json
  lang/it.json
  src/packs/macros/folders_Custom_Time_Chat_Message_Formatter_HkvwQscI8Ojojlca.yml
  src/packs/macros/macros_customChatTimeFormatter_hw8xKGOwvdSpa5uw.yml
  src/settings.mjs
  src/timeteller.mjs
Labels: core feature

#343 Added await and try/catch around call to time change handler macro, so that errors in user time change macros are more obvious in the console.
  src/timekeeper.mjs
Labels: bug

#344 Removed the border around the window header on the floating UI panel. It looked particularly ugly with light theme colours.
  styles/easy-timekeeping.css
Labels: refactoring

#345 Update it.json
  lang/it.json
Labels: core feature
